# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

##### load rules #####


include: "rules/NODDIpipeline.smk"


##### target rules #####


rule all:
    input:
        get_converted_nii(),
